### ISSUE TITLE
Support for topic to accept values other than just compact and delete in case of log compaction the topic should be set to [compact,delete]

### ISSUE THREAD

**Issue by deric18** [advertine/kafka-tools#2]
A kafka topic has to be set to [compact,delete] in case when kafka log compaction is enabled which is not supported yet by the latest version of the repo. please take a look

**Comment by royaltm** [comment]
Could you elaborate more?

**Comment by deric18** [comment]
while creating or configuring a kafka topic , you should be able to set the the cleanup.policy property of the topic to either compact or delete or in case of log compaction to both [compact,delete] , the first two cases are supported in the current version of the code but it doesn't support the both [compact,delete] option. which needs to be updated. Let me know if you have further questions.

**Comment by royaltm** [comment]
hmmm, according to: https://kafka.apache.org/documentation/#topicconfigs it doesn't mention a possibility to setup both at the same time, but I see it was introduced later: https://cwiki.apache.org/confluence/display/KAFKA/KIP-71%3A+Enable+log+compaction+and+deletion+to+co-exist
ok, so it makes sense now, thanks for the issue

**Comment by royaltm** [comment]
@deric18 I've upadated master, please check if it works for you.

**Comment by deric18** [comment]
hey @royaltm : i took a look at the PR , could you also add [delete,compact] to the set of valid values as any permutation of compact,delete can be valid value for policy.cleanup and my API can be consumed by anybody so i should be flexible to offer that.

**Comment by royaltm** [comment]
thanks for the PR, merged.

**Comment by deric18** [comment]
thanks.

**Comment by deric18** [comment]
hey @royaltm : Can you publish the package with all the fixes.

**Comment by royaltm** [comment]
sure

**Comment by deric18** [comment]
thanks.
